name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      USER: root
    steps:
      - uses: actions/checkout@v2

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "production"
        env:
          SEGMENT_API_KEY: ${{ secrets.SEGMENT_API_KEY }}
          SENTRY_PROJECT_ID: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_KEY: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Create Deployment
        id: deploy
        uses: abendigo/create-deployment@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create a Sentry.io release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_LOG_LEVEL: info
        with:
          environment: production
          version: $(git rev-parse --short HEAD)
