name: Deploy CDN Proxy

on:
  push:
    branches:
      - main
    paths:
      - 'cdn/**/*'

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Deploy
        env:
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          USER: root
        steps:
          - uses: actions/checkout@v2

          - name: Publish
            uses: cloudflare/wrangler-action@1.1.0
            with:
              apiToken: ${{ secrets.CF_API_TOKEN }}
              workingDirectory: 'cdn'
              environment: production


          - name: Create Deployment
            id: deploy
            uses: abendigo/create-deployment@v1
            with:
              token: ${{ secrets.GITHUB_TOKEN }}
          
          - name: Create a Sentry.io release
            uses: tclindner/sentry-releases-action@v1.0.0
            env:
              SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
              SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
              SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
            with:
              tagName: ${{ github.sha }}
              environment: production