name: Deploy Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      USER: root
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Publish
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          environment: "production"
        env:
          SEGMENT_API_KEY: ${{ secrets.SEGMENT_API_KEY }}
          SENTRY_PROJECT_ID: ${{ secrets.SENTRY_PROJECT }}
          SENTRY_KEY: ${{ secrets.SENTRY_AUTH_TOKEN }}

